spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authservice
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Optional: you can adjust based on your requirement
    continue-on-error: true
    initialize: true

  jpa:
    hibernate:
      ddl-auto: update  # Optional: use 'none', 'update', 'create', or 'create-drop'
    show-sql: true      # Optional: shows SQL queries in the console during development
    properties:
      hibernate:
        format_s  ql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  topic:
    name: testing_json
  producer:
    bootstrap-servers: localhost:2181
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: AuthService.serializer.UserInfoSerializer

#  consumer:
#    bootstrap-servers: localhost:2181
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer